services:
  subscription-service:
    build: ./
    volumes:
      - ./migrations:/app/migrations
    env_file:
      - .env
    container_name: subscription_service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - subscription_service_network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    container_name: subscription_service_db
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5433:${DB_PORT}"
    networks:
      - subscription_service_network

networks:
  subscription_service_network: